Traceback (most recent call last):
  File "/mnt/lustre/groups/link/linca945/MStoML/skripts/FIA/VAE_smac.py", line 4, in <module>
    from VAE import *
  File "/mnt/lustre/groups/link/linca945/MStoML/skripts/FIA/VAE.py", line 14, in <module>
    from sklearn.model_selection import train_test_split
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/sklearn/__init__.py", line 87, in <module>
    from .base import clone
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from ._estimator_html_repr import estimator_html_repr
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/sklearn/utils/_estimator_html_repr.py", line 10, in <module>
    from .fixes import parse_version
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 17, in <module>
    import scipy.stats
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/stats/__init__.py", line 605, in <module>
    from ._stats_py import *
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/stats/_stats_py.py", line 45, in <module>
    from . import distributions
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/stats/_distn_infrastructure.py", line 23, in <module>
    from scipy import optimize
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/optimize/__init__.py", line 425, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
    from ._linprog_highs import _linprog_highs
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-311-x86_64-linux-gnu.so)
Done
