['../../runs/FIA/comm8/oms', '../../runs/VAE/hyperband_optimization']
/mnt/lustre/groups/link/linca945/MStoML/skripts/FIA
Traceback (most recent call last):
  File "/mnt/lustre/groups/link/linca945/MStoML/skripts/FIA/VAE_smac.py", line 117, in <module>
    __main__()
  File "/mnt/lustre/groups/link/linca945/MStoML/skripts/FIA/VAE_smac.py", line 37, in __main__
    binned_dfs = pd.read_csv(os.path.join(data_dir, "data_matrix.tsv"), sep="\t", index_col="mz", engine="pyarrow")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/lustre/groups/link/linca945/.conda/envs/MStoML/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/lustre/groups/link/linca945/MStoML/runs/FIA/comm8/oms/data_matrix.tsv'
Done
